Generowanie i pobieranie raportu w API + migracje i modele
infoshareacademy/jcszr4-HoneyBadgers pull request #38
Opened 2022-03-12 16:32 UTC by wisniewski-patryk

Zaraz poszukam czemu merge nie przechodzi :) w każdym razie review można zacząć działać ;)

2022-03-13 10:04 UTC, BeataG requested changes
Nie ma nawigacji do Twojej strony z raportami, usunąłeś moje strony - prawdopodobnie nie budowałeś z najnowszej wersji mastera. Brak zabezpieczeń przed wejściem na stronę jeśli nie jesteś adminem.
Ale ogólnie kod napisany schludnie

2022-03-13 10:27 UTC, wisniewski-patryk commented on HoneyBadgers.Logic/Services/ReportService.cs
> +        //TODO: get
Jest w ReportService w WebApi. `TODO' nie w tym miejscu wpisalem co powinienem. Zwracam troche wiekszy model z Tuplem miedzy innymi. 
Zapisze sobie do poprawy

2022-03-13 12:33 UTC, wisniewski-patryk commented
Ok, mam nadzieje, że wszystko poprawiłem i przywróciłem co popsułem. 

Zostały TODO do poprawienia i kilka komentarzy. zajmę się tym po egzaminie

2022-03-13 12:33 UTC, wisniewski-patryk commented on HoneyBadgers.Logic/Services/ReportService.cs
> +        //TODO: get
był w zły miejscu :)

2022-03-16 19:12 UTC, BeataG approved these changes

2022-03-16 19:18 UTC, merged